### PR TITLE
Permit force env in production

### PR DESCRIPTION
**Pull request by EduardoRFS**
Like @jonathanong talked 

> would be better if env could be passed via options

### CODE REVIEW

**Comment by jonathanong** [comment]
@EduardoRFS would you like to maintain this library?

**Comment by EduardoRFS** [comment]
@jonathanong if isn't a problem, yes

**Comment by jonathanong** [comment]
@EduardoRFS what's your npm username?

**Comment by EduardoRFS** [comment]
@jonathanong eduardorfs ... I'm a creative person

**Pull request merged**
